# Generated by Django 5.1.5 on 2025-04-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysisresult",
            name="artifact_detection",
        ),
        migrations.RemoveField(
            model_name="analysisresult",
            name="confidence",
        ),
        migrations.RemoveField(
            model_name="analysisresult",
            name="facial_consistency",
        ),
        migrations.RemoveField(
            model_name="analysisresult",
            name="image",
        ),
        migrations.RemoveField(
            model_name="analysisresult",
            name="is_fake",
        ),
        migrations.RemoveField(
            model_name="analysisresult",
            name="texture_analysis",
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="confidence_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="media_file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="methods",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="recommendations",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="summary",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="analysisresult",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
